import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito, Rubik } from "next/font/google";
import "./globals.css";
import { Header, Footer } from "@/components/shared";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700', '800', '900'],
});

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${rubik.className} antialiased`}>
        <main className="min-h-screen  w-full" >
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
